sudo: required
services:
 - docker

before_install:
 - docker build -t mark/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true mark/react-test npm test

after_success:
 - docker build -t multi-client ./client
 - docker build -t multi-nginx ./nginx
 - docker build -t multi-api ./api
 - docker build -t multi-worker ./worker

 #Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # Take those images and push them to docker hub
 - docker tag local-image:multi-client new-repo:multi-client
 - docker tag local-image:multi-nginx new-repo:multi-nginx
 - docker tag local-image:multi-api new-repo:multi-api
 - docker tag local-image:multi-worker new-repo:multi-worker
 - docker push new-repo:multi-client
 - docker push new-repo:multi-nginx
 - docker push new-repo:multi-api
 - docker push new-repo:multi-worker