name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mark/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mark/react-test npm test

      - run: docker build -t mark/multi-client ./client
      - run: docker build -t mark/multi-nginx ./nginx
      - run: docker build -t mark/multi-server ./server
      - run: docker build -t mark/multi-worker ./worker

      - run: docker image tag  mark/multi-client tsoialeksei17537/multi-client
      - run: docker image tag  mark/multi-nginx tsoialeksei17537/multi-nginx
      - run: docker image tag  mark/multi-server tsoialeksei17537/multi-server
      - run: docker image tag  mark/multi-worker tsoialeksei17537/multi-worker


      - run: docker push tsoialeksei17537/multi-client
      - run: docker push tsoialeksei17537/multi-nginx
      - run: docker push tsoialeksei17537/multi-server
      - run: docker push tsoialeksei17537/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
     
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-211125608529
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip