name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mark/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mark/react-test npm test

      - run: docker build -t mark/multi-client ./client
      - run: docker build -t mark/multi-nginx ./nginx
      - run: docker build -t mark/multi-server ./server
      - run: docker build -t mark/multi-worker ./worker

      - run: docker image tag mark/multi-client multi-client
      - run: docker image tag mark/multi-nginx multi-nginx
      - run: docker image tag mark/multi-server multi-server
      - run: docker image tag mark/multi-worker multi-worker


      - run: docker image push multi-client
      - run: docker image push multi-nginx
      - run: docker image push multi-server
      - run: docker image push multi-worker